services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    command: tail -f /dev/null

  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.duckdb:/app/mlflow.duckdb
    command:
      - uv
      - run
      - mlflow
      - server
      - --backend-store-uri
      - sqlite:///mlflow.duckdb
      - --default-artifact-root
      - ./mlruns
      - --host
      - 0.0.0.0
      - --port
      - '5000'
      - --serve-artifacts
