site_name: Real-Time Fraud Detection API
site_description: Project documentation for the Real-Time Fraud Detection API.

nav:
  - 'Home': 'index.md'
  - 'Usage Guide': 'usage.md'
  - 'Business': 'business.md'
  - 'Project Files': 'project_files.md'
  - 'Logging': 'logging.md'
  - 'Testing Strategy': 'testing.md'

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
