# General project configuration
project_name: "ml_fraud_detection"
environment: "development" # Default environment

# Paths
data:
  raw_path: "data/raw/fraud_data.csv"
  processed_path: "data/processed/processed_transactions.parquet"
  raw_profile_path: "data/reports/raw_data_profile.json"
  processed_profile_path: "data/reports/processed_data_profile.json"
  train_dataset_path: "data/processed/train_dataset.parquet"
  test_dataset_path: "data/processed/test_dataset.parquet"

# Data setup configuration
data_setup:
  gdrive_file_id: "1oR8ZVcF_ifwKiyzRXlre1nZMM0WVp57E"
  download_path: "data/download"
  num_rows_to_select: 600000

# MLflow configuration
mlflow:
  experiment_name: "100525_random_forest_gs" # Change this for each experiment
  tracking_uri: "sqlite:///mlflow.duckdb" # Default local tracking
  artifact_root: "./mlruns"

# Data splitting configuration
data_splitting:
  test_size: 0.2 # The 20% for the final hold-out validation set
  timestamp_col: "step"

# Model training configuration
model_training:
  exp_name_prefix: "test"
  run_name_prefix: "test"
  cv_strategy: "TimeSeriesSplit"
  cv_folds: 5
  skip_folds: 4
  number_of_rows: null
  models_to_compare:
    - "xgboost"
    - "randomforest"
    - "lightgbm"
  target_variable: "isFraud"
  features_to_drop:
    - "step"
    - "nameOrig"
    - "nameDest"
    - "event_timestamp"
  model_params:
    randomforest:
      random_state: 42
      class_weight: "balanced"
      n_estimators: 100 # 100
      criterion: "gini" # "gini"
      max_depth: null # null
      min_samples_split: 2 # 2
      min_samples_leaf: 1 # 1
      min_weight_fraction_leaf: 0.0 # 0.0
      max_features: "sqrt" # "sqrt"
      max_leaf_nodes: null # null
      min_impurity_decrease: 0.0 # 0.0
      bootstrap: True # True
      oob_score: False # False
    xgboost:
      random_state: 42
      eval_metric: "logloss"
      n_estimators: 100 # 100
      max_depth: 6 # 6
      learning_rate: 0.3 # 0.3
      min_child_weight: 1 # 1
      gamma: 0.0 # 0
      subsample: 1.0 # 1
      colsample_bytree: 1.0 # 1
      colsample_bylevel: 1 # 1
      colsample_bynode: 1 # 1
      reg_alpha: 0.0 # 0
      reg_lambda: 1.0 # 1
      max_delta_step: 0 # 0
    lightgbm:
      random_state: 42
      class_weight: "balanced"
      boosting_type: "gbdt" # "gbdt"
      n_estimators: 100 # 100
      max_depth: -1 # -1
      learning_rate: 0.1 # 0.1
      num_leaves: 31 # 31
      min_child_samples: 20 # 20
      min_split_gain: 0.0 # 0.0
      min_child_weight: 0.001 # 0.001
      subsample: 1.0 # 1.0
      subsample_freq: 0 # 0
      colsample_bytree: 1.0 # 1.0
      reg_alpha: 0.0 # 0.0
      reg_lambda: 0.0 # 0.0

# Grid Search training configuration
  model_gs: "randomforest" # Model to use for Grid Search: "randomforest", "xgboost", "lightgbm"
  param_grid:
    n_estimators: [100, 200]
    max_depth: [10, 20, null]
    learning_rate: [0.05, 0.1, 0.2]  # XGBoost, LightGBM
    min_child_weight: [1, 5]         # XGBoost, LightGBM
    subsample: [0.8, 1.0]            # XGBoost, LightGBM
    colsample_bytree: [0.8, 1.0]     # XGBoost, LightGBM
    reg_alpha: [0.0, 0.1]            # XGBoost, LightGBM
    reg_lambda: [0.0, 0.1]           # XGBoost, LightGBM
    min_samples_split: [2, 5]        # RandomForest
    min_samples_leaf: [1, 2]         # RandomForest
    max_features: ["sqrt", "log2"]   # RandomForest
    gamma: [0.0, 0.1]                # XGBoost
    num_leaves: [31, 50]             # LightGBM
    min_child_samples: [20, 50]      # LightGBM
