# General project configuration
project_name: "ml_fraud_detection"
environment: "development" # Default environment

# Paths
data:
  raw_path: "data/raw/fraud_data.csv"
  processed_path: "data/processed/processed_transactions.parquet"
  raw_profile_path: "data/reports/raw_data_profile.json"
  processed_profile_path: "data/reports/processed_data_profile.json"

# MLflow configuration
mlflow:
  experiment_name: "fraud_detection"
  tracking_uri: "sqlite:///mlflow.duckdb" # Default local tracking
  artifact_root: "./mlruns"
