name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Create Virtual Environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e .[dev,notebook]

      - name: Run linter
        run: make lint

      - name: Debug Structlog Installation
        run: |
          uv run python -c "import structlog; print(f'structlog version: {structlog.__version__}'); print('--- dir(structlog) ---'); print(dir(structlog)); print('--- dir(structlog.typing) ---'); import structlog.typing; print(dir(structlog.typing))"

      - name: Run type checker
        run: make type-check

      - name: Run tests
        run: make test
